name: '#myMODO'
favicon: null
layout_spectrum: 0.75344
typography_spectrum: 0.50391
title: HELLO MODO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006203'
    - '#a4fba6'
    - '#0f9200'
    - '#30cb00'
    - '#4ae54a'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
