name: '#myMODO'
favicon: null
layout_spectrum: 0.69862
typography_spectrum: 0.50391
title: HELLO MODO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5aa02c'
    - '#008000'
    - '#000000'
    - '#00ff00'
    - '#555500'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
