name: '#myMODO'
favicon: null
layout_spectrum: 0.74561
typography_spectrum: 0.50391
title: HELLO MODO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5aa02c'
    - '#ffffff'
    - '#20d1f7'
    - '#9deafb'
    - '#97c37b'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
