name: MODO
favicon: null
layout_spectrum: 0.3709
typography_spectrum: 0.47737
title: HELLO MODO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006203'
    - '#a4fba6'
    - '#0f9200'
    - '#30cb00'
    - '#4ae54a'
  brandStrength: 0.5625
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
